version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - fmt.Sscanf
    staticcheck:
      checks:
        - "all"
        - "-QF1008"
        - "-ST1000"
        - "-ST1003"

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
