name: ci

on:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Qt6 dependencies
        run: sudo apt-get update && sudo apt-get install -y qt6-base-dev

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: 
          echo "Takes few minutes to build dependency github.com/mappu/miqt/qt6"
          go build ./...

      - name: Test
        run: go test ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
