// Seed data extracted from internal/migrations/0001_initial.sql.
// Called during onCreate to pre-populate designations and domains.

import 'package:drift/drift.dart';

Future<void> seedDatabase(GeneratedDatabase db) async {
  // French AOC/AOP designations from the INAO SIQO reference list.
  await db.customStatement('''
INSERT OR IGNORE INTO designations (name, region) VALUES
    ('Alsace', 'Alsace'),
    ('Alsace Grand Cru', 'Alsace'),
    ('Crémant d''Alsace', 'Alsace'),
    ('Beaujolais', 'Beaujolais'),
    ('Beaujolais Villages', 'Beaujolais'),
    ('Brouilly', 'Beaujolais'),
    ('Chénas', 'Beaujolais'),
    ('Chiroubles', 'Beaujolais'),
    ('Côte de Brouilly', 'Beaujolais'),
    ('Fleurie', 'Beaujolais'),
    ('Juliénas', 'Beaujolais'),
    ('Morgon', 'Beaujolais'),
    ('Moulin-à-Vent', 'Beaujolais'),
    ('Régnié', 'Beaujolais'),
    ('Saint-Amour', 'Beaujolais'),
    ('Barsac', 'Bordeaux'),
    ('Blaye', 'Bordeaux'),
    ('Blaye Côtes de Bordeaux', 'Bordeaux'),
    ('Bordeaux', 'Bordeaux'),
    ('Bordeaux Clairet', 'Bordeaux'),
    ('Bordeaux Rosé', 'Bordeaux'),
    ('Bordeaux Sec', 'Bordeaux'),
    ('Bordeaux Supérieur', 'Bordeaux'),
    ('Bourg', 'Bordeaux'),
    ('Cadillac', 'Bordeaux'),
    ('Cadillac Côtes de Bordeaux', 'Bordeaux'),
    ('Canon-Fronsac', 'Bordeaux'),
    ('Castillon Côtes de Bordeaux', 'Bordeaux'),
    ('Cérons', 'Bordeaux'),
    ('Côtes de Bordeaux Saint-Macaire', 'Bordeaux'),
    ('Crémant de Bordeaux', 'Bordeaux'),
    ('Entre-deux-Mers', 'Bordeaux'),
    ('Entre-deux-Mers Haut-Benauge', 'Bordeaux'),
    ('Francs Côtes de Bordeaux', 'Bordeaux'),
    ('Fronsac', 'Bordeaux'),
    ('Graves', 'Bordeaux'),
    ('Graves de Vayres', 'Bordeaux'),
    ('Graves Supérieures', 'Bordeaux'),
    ('Haut-Médoc', 'Bordeaux'),
    ('Lalande-de-Pomerol', 'Bordeaux'),
    ('Listrac-Médoc', 'Bordeaux'),
    ('Loupiac', 'Bordeaux'),
    ('Lussac Saint-Émilion', 'Bordeaux'),
    ('Margaux', 'Bordeaux'),
    ('Médoc', 'Bordeaux'),
    ('Montagne Saint-Émilion', 'Bordeaux'),
    ('Moulis', 'Bordeaux'),
    ('Pauillac', 'Bordeaux'),
    ('Pessac-Léognan', 'Bordeaux'),
    ('Pomerol', 'Bordeaux'),
    ('Puisseguin Saint-Émilion', 'Bordeaux'),
    ('Sainte-Croix-du-Mont', 'Bordeaux'),
    ('Sainte-Foy Bordeaux', 'Bordeaux'),
    ('Saint-Émilion', 'Bordeaux'),
    ('Saint-Émilion Grand Cru', 'Bordeaux'),
    ('Saint-Estèphe', 'Bordeaux'),
    ('Saint-Georges Saint-Émilion', 'Bordeaux'),
    ('Saint-Julien', 'Bordeaux'),
    ('Sauternes', 'Bordeaux'),
    ('Auxey-Duresses', 'Bourgogne'),
    ('Bâtard-Montrachet', 'Bourgogne'),
    ('Beaune', 'Bourgogne'),
    ('Bienvenues-Bâtard-Montrachet', 'Bourgogne'),
    ('Blagny', 'Bourgogne'),
    ('Bonnes-Mares', 'Bourgogne'),
    ('Bourgogne', 'Bourgogne'),
    ('Bourgogne Aligoté', 'Bourgogne'),
    ('Bourgogne Chitry', 'Bourgogne'),
    ('Bourgogne Côte Chalonnaise', 'Bourgogne'),
    ('Bourgogne Côte d''Or', 'Bourgogne'),
    ('Bourgogne Côtes du Couchois', 'Bourgogne'),
    ('Bourgogne Épineuil', 'Bourgogne'),
    ('Bourgogne Hautes-Côtes de Beaune', 'Bourgogne'),
    ('Bourgogne Hautes-Côtes de Nuits', 'Bourgogne'),
    ('Bourgogne Irancy', 'Bourgogne'),
    ('Bourgogne La Chapelle Notre-Dame', 'Bourgogne'),
    ('Bourgogne Le Chapitre', 'Bourgogne'),
    ('Bourgogne Montrecul', 'Bourgogne'),
    ('Bourgogne Passe-tout-grains', 'Bourgogne'),
    ('Bourgogne Tonnerre', 'Bourgogne'),
    ('Bouzeron', 'Bourgogne'),
    ('Chablis', 'Bourgogne'),
    ('Chablis Grand Cru', 'Bourgogne'),
    ('Chablis Premier Cru', 'Bourgogne'),
    ('Chambertin', 'Bourgogne'),
    ('Chambertin-Clos-de-Bèze', 'Bourgogne'),
    ('Chambolle-Musigny', 'Bourgogne'),
    ('Chapelle-Chambertin', 'Bourgogne'),
    ('Charlemagne', 'Bourgogne'),
    ('Charmes-Chambertin', 'Bourgogne'),
    ('Chassagne-Montrachet', 'Bourgogne'),
    ('Chevalier-Montrachet', 'Bourgogne'),
    ('Chorey-lès-Beaune', 'Bourgogne'),
    ('Clos de la Roche', 'Bourgogne'),
    ('Clos de Tart', 'Bourgogne'),
    ('Clos de Vougeot', 'Bourgogne'),
    ('Clos des Lambrays', 'Bourgogne'),
    ('Clos Saint-Denis', 'Bourgogne'),
    ('Corton', 'Bourgogne'),
    ('Corton-Charlemagne', 'Bourgogne'),
    ('Côte de Beaune', 'Bourgogne'),
    ('Côte de Beaune-Villages', 'Bourgogne'),
    ('Côte de Nuits-Villages', 'Bourgogne'),
    ('Criots-Bâtard-Montrachet', 'Bourgogne'),
    ('Échézeaux', 'Bourgogne'),
    ('Fixin', 'Bourgogne'),
    ('Gevrey-Chambertin', 'Bourgogne'),
    ('Grands-Échézeaux', 'Bourgogne'),
    ('Griottes-Chambertin', 'Bourgogne'),
    ('La Grande Rue', 'Bourgogne'),
    ('La Romanée', 'Bourgogne'),
    ('La Tâche', 'Bourgogne'),
    ('Ladoix', 'Bourgogne'),
    ('Latricières-Chambertin', 'Bourgogne'),
    ('Mâcon', 'Bourgogne'),
    ('Mâcon-Villages', 'Bourgogne'),
    ('Maranges', 'Bourgogne'),
    ('Marsannay', 'Bourgogne'),
    ('Mazis-Chambertin', 'Bourgogne'),
    ('Mazoyères-Chambertin', 'Bourgogne'),
    ('Mercurey', 'Bourgogne'),
    ('Meursault', 'Bourgogne'),
    ('Montagny', 'Bourgogne'),
    ('Monthélie', 'Bourgogne'),
    ('Montrachet', 'Bourgogne'),
    ('Morey-Saint-Denis', 'Bourgogne'),
    ('Musigny', 'Bourgogne'),
    ('Nuits-Saint-Georges', 'Bourgogne'),
    ('Pernand-Vergelesses', 'Bourgogne'),
    ('Petit Chablis', 'Bourgogne'),
    ('Pommard', 'Bourgogne'),
    ('Pouilly-Fuissé', 'Bourgogne'),
    ('Pouilly-Loché', 'Bourgogne'),
    ('Pouilly-Vinzelles', 'Bourgogne'),
    ('Puligny-Montrachet', 'Bourgogne'),
    ('Richebourg', 'Bourgogne'),
    ('Romanée-Conti', 'Bourgogne'),
    ('Romanée-Saint-Vivant', 'Bourgogne'),
    ('Ruchottes-Chambertin', 'Bourgogne'),
    ('Rully', 'Bourgogne'),
    ('Saint-Aubin', 'Bourgogne'),
    ('Saint-Romain', 'Bourgogne'),
    ('Saint-Véran', 'Bourgogne'),
    ('Santenay', 'Bourgogne'),
    ('Savigny-lès-Beaune', 'Bourgogne'),
    ('Viré-Clessé', 'Bourgogne'),
    ('Volnay', 'Bourgogne'),
    ('Vosne-Romanée', 'Bourgogne'),
    ('Vougeot', 'Bourgogne'),
    ('Champagne', 'Champagne'),
    ('Coteaux Champenois', 'Champagne'),
    ('Rosé des Riceys', 'Champagne'),
    ('Ajaccio', 'Corse'),
    ('Corse', 'Corse'),
    ('Corse Calvi', 'Corse'),
    ('Corse Coteaux du Cap Corse', 'Corse'),
    ('Corse Figari', 'Corse'),
    ('Corse Porto-Vecchio', 'Corse'),
    ('Corse Sartène', 'Corse'),
    ('Muscat du Cap Corse', 'Corse'),
    ('Patrimonio', 'Corse'),
    ('Arbois', 'Jura'),
    ('Château-Chalon', 'Jura'),
    ('Côtes du Jura', 'Jura'),
    ('Crémant du Jura', 'Jura'),
    ('L''Étoile', 'Jura'),
    ('Macvin du Jura', 'Jura'),
    ('Cabardès', 'Languedoc'),
    ('Clairette de Bellegarde', 'Languedoc'),
    ('Clairette du Languedoc', 'Languedoc'),
    ('Corbières', 'Languedoc'),
    ('Corbières-Boutenac', 'Languedoc'),
    ('Costières de Nîmes', 'Languedoc'),
    ('Coteaux du Languedoc', 'Languedoc'),
    ('Faugères', 'Languedoc'),
    ('Fitou', 'Languedoc'),
    ('Languedoc', 'Languedoc'),
    ('Limoux', 'Languedoc'),
    ('Malepère', 'Languedoc'),
    ('Minervois', 'Languedoc'),
    ('Minervois-La Livinière', 'Languedoc'),
    ('Muscat de Frontignan', 'Languedoc'),
    ('Muscat de Lunel', 'Languedoc'),
    ('Muscat de Mireval', 'Languedoc'),
    ('Muscat de Saint-Jean-de-Minervois', 'Languedoc'),
    ('Pic Saint-Loup', 'Languedoc'),
    ('Saint-Chinian', 'Languedoc'),
    ('Terrasses du Larzac', 'Languedoc'),
    ('Anjou', 'Loire'),
    ('Anjou Coteaux de la Loire', 'Loire'),
    ('Anjou Gamay', 'Loire'),
    ('Anjou Villages', 'Loire'),
    ('Anjou Villages Brissac', 'Loire'),
    ('Bonnezeaux', 'Loire'),
    ('Bourgueil', 'Loire'),
    ('Cheverny', 'Loire'),
    ('Chinon', 'Loire'),
    ('Coteaux de l''Aubance', 'Loire'),
    ('Coteaux de Saumur', 'Loire'),
    ('Coteaux du Giennois', 'Loire'),
    ('Coteaux du Layon', 'Loire'),
    ('Coteaux du Loir', 'Loire'),
    ('Coteaux du Vendômois', 'Loire'),
    ('Cour-Cheverny', 'Loire'),
    ('Crémant de Loire', 'Loire'),
    ('Fiefs Vendéens', 'Loire'),
    ('Gros Plant du Pays Nantais', 'Loire'),
    ('Haut-Poitou', 'Loire'),
    ('Jasnières', 'Loire'),
    ('Menetou-Salon', 'Loire'),
    ('Montlouis-sur-Loire', 'Loire'),
    ('Muscadet', 'Loire'),
    ('Muscadet Coteaux de la Loire', 'Loire'),
    ('Muscadet Côtes de Grandlieu', 'Loire'),
    ('Muscadet Sèvre et Maine', 'Loire'),
    ('Orléans', 'Loire'),
    ('Orléans-Cléry', 'Loire'),
    ('Pouilly-Fumé', 'Loire'),
    ('Pouilly-sur-Loire', 'Loire'),
    ('Quarts de Chaume', 'Loire'),
    ('Quincy', 'Loire'),
    ('Reuilly', 'Loire'),
    ('Rosé d''Anjou', 'Loire'),
    ('Rosé de Loire', 'Loire'),
    ('Saint-Nicolas-de-Bourgueil', 'Loire'),
    ('Sancerre', 'Loire'),
    ('Saumur', 'Loire'),
    ('Saumur Champigny', 'Loire'),
    ('Saumur Puy-Notre-Dame', 'Loire'),
    ('Savenières', 'Loire'),
    ('Savenières Coulée-de-Serrant', 'Loire'),
    ('Savenières Roche-aux-Moines', 'Loire'),
    ('Touraine', 'Loire'),
    ('Touraine Amboise', 'Loire'),
    ('Touraine Azay-le-Rideau', 'Loire'),
    ('Touraine Chenonceaux', 'Loire'),
    ('Touraine Mesland', 'Loire'),
    ('Touraine Noble Joué', 'Loire'),
    ('Touraine Oisly', 'Loire'),
    ('Valencay', 'Loire'),
    ('Vouvray', 'Loire'),
    ('Bandol', 'Provence'),
    ('Bellet', 'Provence'),
    ('Cassis', 'Provence'),
    ('Coteaux d''Aix-en-Provence', 'Provence'),
    ('Coteaux de Pierrevert', 'Provence'),
    ('Coteaux Varois en Provence', 'Provence'),
    ('Côtes de Provence', 'Provence'),
    ('Les Baux de Provence', 'Provence'),
    ('Muscat du Beaumes-de-Venise', 'Provence'),
    ('Palette', 'Provence'),
    ('Beaumes-de-Venise', 'Rhône'),
    ('Brézème', 'Rhône'),
    ('Châteauneuf-du-Pape', 'Rhône'),
    ('Clairette de Die', 'Rhône'),
    ('Condrieu', 'Rhône'),
    ('Cornas', 'Rhône'),
    ('Côte-Rôtie', 'Rhône'),
    ('Coteaux de Die', 'Rhône'),
    ('Coteaux du Tricastin', 'Rhône'),
    ('Côtes du Rhône', 'Rhône'),
    ('Côtes du Rhône Villages', 'Rhône'),
    ('Côtes du Ventoux', 'Rhône'),
    ('Côtes du Vivarais', 'Rhône'),
    ('Crémant de Die', 'Rhône'),
    ('Crozes-Hermitage', 'Rhône'),
    ('Gigondas', 'Rhône'),
    ('Grignan-les-Adhémar', 'Rhône'),
    ('Hermitage', 'Rhône'),
    ('Lirac', 'Rhône'),
    ('Luberon', 'Rhône'),
    ('Muscat de Beaumes-de-Venise', 'Rhône'),
    ('Rasteau', 'Rhône'),
    ('Saint-Joseph', 'Rhône'),
    ('Saint-Péray', 'Rhône'),
    ('Tavel', 'Rhône'),
    ('Vacqueyras', 'Rhône'),
    ('Ventoux', 'Rhône'),
    ('Vinsobres', 'Rhône'),
    ('Banyuls', 'Roussillon'),
    ('Banyuls Grand Cru', 'Roussillon'),
    ('Collioure', 'Roussillon'),
    ('Côtes du Roussillon', 'Roussillon'),
    ('Côtes du Roussillon Villages', 'Roussillon'),
    ('Côtes du Roussillon Villages Caramany', 'Roussillon'),
    ('Côtes du Roussillon Villages Latour-de-France', 'Roussillon'),
    ('Côtes du Roussillon Villages Les Aspres', 'Roussillon'),
    ('Côtes du Roussillon Villages Lesquerde', 'Roussillon'),
    ('Côtes du Roussillon Villages Tautavel', 'Roussillon'),
    ('Maury', 'Roussillon'),
    ('Muscat de Rivesaltes', 'Roussillon'),
    ('Rivesaltes', 'Roussillon'),
    ('Bugey', 'Savoie'),
    ('Crémant de Savoie', 'Savoie'),
    ('Roussette de Bugey', 'Savoie'),
    ('Roussette de Savoie', 'Savoie'),
    ('Seyssel', 'Savoie'),
    ('Vin de Savoie', 'Savoie'),
    ('Béarn', 'Sud-Ouest'),
    ('Bergerac', 'Sud-Ouest'),
    ('Buzet', 'Sud-Ouest'),
    ('Cahors', 'Sud-Ouest'),
    ('Côtes du Marmandais', 'Sud-Ouest'),
    ('Côtes du Lot', 'Sud-Ouest'),
    ('Entraygues et le Fel', 'Sud-Ouest'),
    ('Estaing', 'Sud-Ouest'),
    ('Fronton', 'Sud-Ouest'),
    ('Gaillac', 'Sud-Ouest'),
    ('Gaillac Premières Côtes', 'Sud-Ouest'),
    ('Irouléguy', 'Sud-Ouest'),
    ('Jurançon', 'Sud-Ouest'),
    ('Madiran', 'Sud-Ouest'),
    ('Marcillac', 'Sud-Ouest'),
    ('Monbazillac', 'Sud-Ouest'),
    ('Montravel', 'Sud-Ouest'),
    ('Pacherenc du Vic-Bilh', 'Sud-Ouest'),
    ('Pécharmant', 'Sud-Ouest'),
    ('Rosette', 'Sud-Ouest'),
    ('Saussignac', 'Sud-Ouest'),
    ('Tursan', 'Sud-Ouest')
''');

  // French wine domains.
  await db.customStatement('''
INSERT OR IGNORE INTO domains (name, description) VALUES
    ('Château Margaux', 'Premier Grand Cru Classé (1855), considéré comme l''un des quatre grands du Médoc. Son Pavillon Rouge et son Pavillon Blanc complètent une gamme d''exception. Adresse : 33460 Margaux-Cantenac. Tél. : +33 5 57 88 83 83.'),
    ('Château Lafite Rothschild', 'Premier Grand Cru Classé du Médoc (1855), propriété de la famille Rothschild depuis 1868. Vins réputés pour leur élégance et leur longévité exceptionnelle. Adresse : 33250 Pauillac. Tél. : +33 5 56 73 18 18.'),
    ('Château Latour', 'Premier Grand Cru Classé, l''un des vins les plus longilignes du Médoc. Le second vin, Les Forts de Latour, offre une porte d''entrée remarquable. Adresse : Saint-Lambert, 33250 Pauillac. Tél. : +33 5 56 73 19 80.'),
    ('Château Mouton Rothschild', 'Seul château élevé au rang de Premier Grand Cru Classé après la classification de 1855 (décret 1973). Célèbre pour ses étiquettes d''artistes et son musée du vin. Adresse : Le Pouyalet, 33250 Pauillac. Tél. : +33 5 56 73 20 20.'),
    ('Château Haut-Brion', 'Seul cru classé hors Médoc dans la classification de 1855 (Pessac-Léognan). Propriété de la famille Dillon. Produit également un blanc parmi les plus recherchés de Bordeaux. Adresse : 135 av. Jean-Jaurès, 33608 Pessac. Tél. : +33 5 56 00 29 30.'),
    ('Château Pichon Baron', 'Deuxième Grand Cru Classé de Pauillac (1855), anciennement Pichon-Longueville Baron. Propriété AXA Millésimes depuis 1987. Adresse : Pichon-Longueville, 33250 Pauillac. Tél. : +33 5 56 73 17 17.'),
    ('Château Pichon Lalande', 'Deuxième Grand Cru Classé de Pauillac (1855), anciennement Pichon-Longueville Comtesse de Lalande. Propriété du groupe Roederer. Adresse : 33250 Pauillac. Tél. : +33 5 56 59 19 40.'),
    ('Château Cos d''Estournel', 'Deuxième Grand Cru Classé de Saint-Estèphe (1855), reconnaissable à ses pagodes orientales. L''un des vins les plus concentrés du Médoc. Adresse : 33180 Saint-Estèphe. Tél. : +33 5 56 73 15 50.'),
    ('Château Léoville Las Cases', 'Deuxième Grand Cru Classé de Saint-Julien (1855), souvent qualifié de « Latour de Saint-Julien ». Le Clos du Marquis constitue le second vin. Adresse : 33250 Saint-Julien-Beychevelle. Tél. : +33 5 56 73 25 26.'),
    ('Château Ducru-Beaucaillou', 'Deuxième Grand Cru Classé de Saint-Julien (1855). Modèle d''élégance et de finesse au sein de l''appellation. Adresse : 33250 Saint-Julien-Beychevelle. Tél. : +33 5 56 73 16 73.'),
    ('Château Palmer', 'Troisième Grand Cru Classé de Margaux (1855), régulièrement hissé au niveau des seconds crus. Co-propriété franco-néerlandaise-britannique. Adresse : 33460 Cantenac. Tél. : +33 5 57 88 72 72.'),
    ('Château Lynch-Bages', 'Cinquième Grand Cru Classé de Pauillac (1855), performance bien au-delà de son rang. Propriété de la famille Cazes. Adresse : 33250 Pauillac. Tél. : +33 5 56 73 24 00.'),
    ('Château Pontet-Canet', 'Cinquième Grand Cru Classé de Pauillac (1855), pionnier de la biodynamie à Bordeaux. Régulièrement coté au niveau des seconds crus. Adresse : 33250 Pauillac. Tél. : +33 5 56 59 04 04.'),
    ('Château Léoville Barton', 'Deuxième Grand Cru Classé de Saint-Julien (1855), propriété de la famille Barton depuis 1826. Rapport qualité-prix réputé imbattable à son niveau. Adresse : 33250 Saint-Julien-Beychevelle. Tél. : +33 5 56 59 06 05.'),
    ('Château d''Yquem', 'Seul Premier Cru Supérieur de la classification des Sauternes (1855). Considéré comme le plus grand vin liquoreux du monde. Propriété LVMH. Adresse : 33210 Sauternes. Tél. : +33 5 57 98 07 07.'),
    ('Château La Mission Haut-Brion', 'Grand Cru Classé de Pessac-Léognan, voisin et rival historique de Haut-Brion, dans la même propriété Dillon depuis 1983. Adresse : 67 rue Peybouquey, 33400 Talence.'),
    ('Château Pape Clément', 'Grand Cru Classé de Pessac-Léognan, l''une des propriétés viticoles les plus anciennes de France (XIVe siècle). Propriété Bernard Magrez. Adresse : 216 av. du Dr Nancel-Pénard, 33600 Pessac. Tél. : +33 5 57 26 38 38.'),
    ('Château Gruaud Larose', 'Deuxième Grand Cru Classé de Saint-Julien (1855), propriété du groupe Alcatel-Lucent (famille Merlaut). Production généreuse et classique. Adresse : 33250 Saint-Julien-Beychevelle. Tél. : +33 5 56 73 15 20.'),
    ('Château Calon Ségur', 'Troisième Grand Cru Classé de Saint-Estèphe (1855), reconnaissable au cœur sur son étiquette. Propriété Capbern Gasqueton. Adresse : 33180 Saint-Estèphe. Tél. : +33 5 56 59 30 08.'),
    ('Château Beychevelle', 'Quatrième Grand Cru Classé de Saint-Julien (1855). Son nom viendrait de « baisse-voile », hommage rendu par les navires à l''amiral de Sourdis. Adresse : 33250 Saint-Julien-Beychevelle. Tél. : +33 5 56 73 20 70.'),
    ('Château Pétrus', 'Pomerol, propriété Jean-Pierre Moueix. Considéré comme l''un des vins les plus rares et chers au monde, produit sur un terroir d''argile pure. Adresse : 33500 Pomerol.'),
    ('Château Cheval Blanc', 'Premier Grand Cru Classé A de Saint-Émilion. Assemblage atypique de Cabernet Franc majoritaire. Co-propriété LVMH – Albert Frère. Adresse : 33330 Saint-Émilion. Tél. : +33 5 57 55 55 55.'),
    ('Château Ausone', 'Premier Grand Cru Classé A de Saint-Émilion, production confidentielle (~20 000 bouteilles/an) sur des pentes calcaires de 7 ha. Adresse : 33330 Saint-Émilion. Tél. : +33 5 57 24 24 57.'),
    ('Vieux Château Certan', 'Pomerol, propriété de la famille Thienpont depuis 1924. L''un des meilleurs Pomerol, Merlot et Cabernet Franc en proportions équilibrées. Adresse : 33500 Pomerol.'),
    ('Château La Conseillante', 'Pomerol, propriété de la famille Nicolas depuis 1871. Voisin de Pétrus, connu pour sa texture soyeuse et son bouquet floral. Adresse : 33500 Pomerol. Tél. : +33 5 57 51 15 32.'),
    ('Château Lafleur', 'Pomerol, 4,5 ha sur les hauteurs du plateau argilo-graveleux. Production rarissime, élevée à côté de Pétrus. Propriété de la famille Guinaudeau. Adresse : 33500 Pomerol.'),
    ('Château Figeac', 'Premier Grand Cru Classé B de Saint-Émilion (promu A en 2022), grande propriété de 40 ha à dominante de Cabernet Franc et Cabernet-Sauvignon. Adresse : 33330 Saint-Émilion. Tél. : +33 5 57 24 72 26.'),
    ('Château Angélus', 'Premier Grand Cru Classé A de Saint-Émilion depuis 2012. Propriété de la famille de Boüard de Laforest. Célèbre pour la cloche sur son étiquette. Adresse : 33330 Saint-Émilion. Tél. : +33 5 57 24 71 39.'),
    ('Château Pavie', 'Premier Grand Cru Classé A de Saint-Émilion depuis 2012. Propriété Gérard Perse. Style opulent et concentré, sur le vignoble le plus étendu du plateau calcaire. Adresse : 33330 Saint-Émilion. Tél. : +33 5 57 55 43 43.'),
    ('Château Troplong Mondot', 'Premier Grand Cru Classé B de Saint-Émilion, point culminant de l''appellation (102 m). Propriété du groupe SCOR. Adresse : 33330 Saint-Émilion. Tél. : +33 5 57 55 32 05.'),
    ('Domaine de la Romanée-Conti', 'Domaine mythique de Vosne-Romanée, propriétaire monopole de La Romanée-Conti et La Tâche. Co-propriété des familles de Villaine et Leroy. Adresse : 1 rue Derrière-le-Four, 21700 Vosne-Romanée. Tél. : +33 3 80 62 48 80.'),
    ('Domaine Leroy', 'Vosne-Romanée, fondé par Lalou Bize-Leroy. Biodynamie intransigeante, rendements dérisoires, vins d''une concentration extrême. L''un des domaines les plus chers de Bourgogne. Adresse : 15 rue de la Fontaine, 21700 Vosne-Romanée.'),
    ('Domaine Armand Rousseau', 'Gevrey-Chambertin, référence absolue en Chambertin et Clos de Bèze. Vins alliant puissance et finesse dans un style classique. Adresse : 1 rue de l''Aumônerie, 21220 Gevrey-Chambertin. Tél. : +33 3 80 34 30 55.'),
    ('Domaine Méo-Camuzet', 'Vosne-Romanée, héritier du savoir-faire d''Henri Jayer, domaine de référence en Clos de Vougeot et Richebourg. Adresse : 11 rue des Grands-Crus, 21700 Vosne-Romanée. Tél. : +33 3 80 61 11 05.'),
    ('Domaine Comte Georges de Vogüé', 'Chambolle-Musigny, propriétaire de 70 % du Musigny et de la totalité de Bonnes-Mares (son apport). L''un des vins les plus délicats de la Côte de Nuits. Adresse : 1 rue de la Barre, 21220 Chambolle-Musigny. Tél. : +33 3 80 62 86 25.'),
    ('Domaine Georges Roumier', 'Chambolle-Musigny, stars : Musigny, Bonnes-Mares, Ruchottes-Chambertin. Christophe Roumier perpétue un style épuré et terroiriste. Adresse : 4 rue de Vergy, 21220 Chambolle-Musigny.'),
    ('Domaine Ponsot', 'Morey-Saint-Denis, dépositaire du monopole Clos des Monts Luisants (blanc). Pionnier de la viticulture biologique en Bourgogne. Adresse : 23 rue de la Montagne, 21220 Morey-Saint-Denis. Tél. : +33 3 80 34 32 46.'),
    ('Domaine Dujac', 'Morey-Saint-Denis, fondé en 1967 par Jacques Seysses. Style élégant, non déstempage partiel, robe translucide. Adresse : 7 rue de la Bussière, 21220 Morey-Saint-Denis. Tél. : +33 3 80 34 01 00.'),
    ('Domaine Mugnier', 'Chambolle-Musigny, propriétaire du monopole Clos de la Maréchale (Nuits) et de parcelles en Musigny et Bonnes-Mares. Frédéric Mugnier produit des vins d''une finesse remarquable. Adresse : Château de Chambolle-Musigny, 21220 Chambolle-Musigny.'),
    ('Domaine Faiveley', 'Nuits-Saint-Georges, l''une des maisons de négoce-propriétaire les plus importantes de Bourgogne. Parcelles en Chambertin, Latricières, Corton. Adresse : 8 rue du Tribourg, 21700 Nuits-Saint-Georges. Tél. : +33 3 80 61 04 55.'),
    ('Domaine Confuron-Cotétidot', 'Vosne-Romanée, vinification traditionnelle non égrappée, vins puissants destinés à une longue garde. Parcelles en Échézeaux et Gevrey premier cru. Adresse : 10 rue de la Fontaine, 21700 Vosne-Romanée.'),
    ('Domaine Leflaive', 'Puligny-Montrachet, référence mondiale en Chardonnay grand cru. Biodynamie depuis 1997, sous la direction d''Anne-Claude Leflaive (†2015). Adresse : Place des Marronniers, 21190 Puligny-Montrachet. Tél. : +33 3 80 21 30 13.'),
    ('Domaine Coche-Dury', 'Meursault, Jean-François Coche-Dury produit des Corton-Charlemagne et Meursault parmi les plus recherchés du monde. Production confidentielle. Adresse : 9 rue Charles-Giraud, 21190 Meursault.'),
    ('Domaine Ramonet', 'Chassagne-Montrachet, spécialiste des grands crus blancs (Montrachet, Bâtard-Montrachet, Bienvenues). Style riche et minéral à la fois. Adresse : 4 place des Noyers, 21190 Chassagne-Montrachet.'),
    ('Domaine Comtes Lafon', 'Meursault, propriété de la famille Lafon. Meursault Perrières et Clos de la Barre parmi les références. Biodynamie depuis 1993. Adresse : Clos de la Barre, 21190 Meursault. Tél. : +33 3 80 21 22 17.'),
    ('Domaine Simon Bize et Fils', 'Savigny-lès-Beaune, Patrick Bize perpétue un style classique bourguignon sur les Vergelesses et Guettes. Adresse : 12 rue du Chanoine Donin, 21420 Savigny-lès-Beaune. Tél. : +33 3 80 21 50 57.'),
    ('Maison Louis Jadot', 'Beaune, l''une des plus importantes maisons de négoce de Bourgogne, présente de Chablis au Mâconnais. Propriétaire de nombreux monopoles dont le Clos des Ursules. Adresse : 21 rue Eugène-Spuller, 21200 Beaune. Tél. : +33 3 80 22 10 57.'),
    ('Maison Joseph Drouhin', 'Beaune, négociant-éleveur présent depuis 1880, propriétaire du Clos des Mouches et de parcelles en Musigny, Chambolle, Chablis. En biodynamie. Adresse : 7 rue d''Enfer, 21200 Beaune. Tél. : +33 3 80 24 68 88.'),
    ('Domaine Bouchard Père et Fils', 'Beaune, plus de 130 ha de vignes dont 12 ha en grands crus. Fondé en 1731, propriété du groupe Champagne Henriot depuis 1995. Adresse : 15 rue du Château, 21200 Beaune. Tél. : +33 3 80 24 80 24.'),
    ('Domaine Jean-Louis Chave', 'Mauves, référence absolue en Hermitage rouge et blanc. Domaine familial depuis le XVe siècle, Jean-Louis Chave perpétue un style intemporel. Adresse : 37 av. du Saint-Joseph, 07300 Mauves. Tél. : +33 4 75 08 24 63.'),
    ('Domaine E. Guigal', 'Ampuis, le domaine phare de la Côte-Rôtie avec ses « La La » (La Mouline, La Landonne, La Turque). Guigal est aussi le premier négociant du Rhône. Adresse : Château d''Ampuis, 69420 Ampuis. Tél. : +33 4 74 56 10 22.'),
    ('Domaine Chapoutier', 'Tain-l''Hermitage, vaste domaine biodynamique présent en Hermitage, Côte-Rôtie, Crozes et en Australie. Les cuvées « Méal » et « L''Ermite » sont des références. Adresse : 18 av. du Docteur-Paul-Durand, 26600 Tain-l''Hermitage. Tél. : +33 4 75 08 28 65.'),
    ('Domaine Paul Jaboulet Aîné', 'Tain-l''Hermitage, fondé en 1834. La Chapelle (Hermitage) est l''un des vins les plus mythiques du Rhône. Propriété de la famille Frey. Adresse : Les Jalets, RN 7, 26600 La Roche-de-Glun. Tél. : +33 4 75 84 68 93.'),
    ('Domaine René Rostaing', 'Ampuis, spécialiste de la Côte-Rôtie et de Condrieu. La Landonne et Côte Blonde figurent parmi les meilleurs Syrah du monde. Adresse : Le Port, 69420 Ampuis.'),
    ('Domaine Jamet', 'Ampuis, propriété de Jean-Paul et Jean-Luc Jamet. Côte-Rôtie d''une précision et d''une élégance rares, élevage long sans excès de bois neuf. Adresse : Le Vallin, 69420 Ampuis.'),
    ('Château Rayas', 'Châteauneuf-du-Pape, production confidentielle sur sables et galets roulés. Le Grenache pur d''Emmanuel Reynaud est considéré comme le plus grand vin de l''appellation. Adresse : 84230 Châteauneuf-du-Pape.'),
    ('Château de Beaucastel', 'Courthézon, l''une des plus grandes propriétés de Châteauneuf-du-Pape (100 ha), célèbre pour ses 13 cépages et son Roussanne Vieilles Vignes. Adresse : Chemin de Beaucastel, 84350 Courthézon. Tél. : +33 4 90 70 41 00.'),
    ('Domaine du Vieux Télégraphe', 'Châteauneuf-du-Pape, référence de l''appellation depuis 1898. La Crau, unique terroir de galets roulés, donne des vins de grande garde. Adresse : 3 route de Châteauneuf-du-Pape, 84370 Bédarrides. Tél. : +33 4 90 33 00 31.'),
    ('Château Pégaü', 'Châteauneuf-du-Pape, propriété Féraud. Style puissant et traditionnel, vendanges entières. La cuvée Réservée et Da Capo sont des références. Adresse : 15 av. Impériale, 84230 Châteauneuf-du-Pape. Tél. : +33 4 90 83 72 70.'),
    ('Domaine Didier Dagueneau', 'Saint-Andelain, révolutionnaire du Pouilly-Fumé. Louis-Benjamin Dagueneau perpétue l''œuvre de son père : Silex, Pur Sang, Buisson Renard, parmi les Sauvignon les plus grands du monde. Adresse : Bourg, 58150 Saint-Andelain.'),
    ('Domaine Henri Bourgeois', 'Chavignol, propriétaire de nombreux crus sancerrois. Exportateur majeur du vignoble depuis plusieurs générations. Présence en Nouvelle-Zélande (Cloudy Bay). Adresse : Chavignol, 18300 Sancerre. Tél. : +33 2 48 78 53 20.'),
    ('Domaine Vacheron', 'Sancerre, biodynamie certifiée, propriété familiale depuis le XVIe siècle. Le Belle Dame et l''Enclos sont des références en rouge. Adresse : 1 rue du Puits Bouillant, 18300 Sancerre. Tél. : +33 2 48 54 09 93.'),
    ('Domaine Huet', 'Vouvray, le domaine emblématique du Chenin Blanc en biodynamie. Le Haut-Lieu, Le Mont et Clos du Bourg en sec, demi-sec ou moelleux. Adresse : 11–13 rue de la Croix-Buisée, 37210 Vouvray. Tél. : +33 2 47 52 78 87.'),
    ('Domaine Nicolas Joly – Coulée de Serrant', 'Savennières, père de la biodynamie viticole moderne. La Coulée de Serrant est un monopole de 7 ha, l''un des rares AOC monoparcellaires de France. Adresse : Château de la Roche aux Moines, 49170 Savennières. Tél. : +33 2 41 72 22 32.'),
    ('Clos Rougeard', 'Chacé (Saumur-Champigny), la propriété culte des frères Foucault, aujourd''hui propriété Martin-Bouygues. Les Poyeux et Le Bourg sont des références mondiales en Cabernet Franc. Adresse : 3 rue du Bourg, 49400 Chacé.'),
    ('Domaine de la Bergerie', 'Rochefort-sur-Loire, spécialiste du Coteaux du Layon et Savennières. Yves Guégniard produit des liquoreux d''une grande finesse. Adresse : La Bergerie, 49290 Rochefort-sur-Loire. Tél. : +33 2 41 78 73 37.'),
    ('Domaine Zind-Humbrecht', 'Turckheim, référence mondiale en biodynamie alsacienne. Olivier Humbrecht MW signe des Riesling et Gewurztraminer de grand cru d''une profondeur exceptionnelle. Adresse : 4 route de Colmar, 68230 Turckheim. Tél. : +33 3 89 27 02 05.'),
    ('Domaine Marcel Deiss', 'Bergheim, Jean-Michel Deiss théorise le « lieu-dit » alsacien et l''assemblage de cépages sur un même terroir. Vins d''une complexité aromatique unique. Adresse : 15 route du Vin, 68750 Bergheim. Tél. : +33 3 89 73 63 37.'),
    ('Domaine Trimbach', 'Ribeauvillé, maison fondée en 1626. Clos Sainte-Hune (Riesling) et Sélection de Grains Nobles sont parmi les blancs les plus recherchés de France. Adresse : 15 route de Bergheim, 68150 Ribeauvillé. Tél. : +33 3 89 73 60 30.'),
    ('Maison Hugel et Fils', 'Riquewihr, fondée en 1639 par Hans Ulrich Hugel. La cuvée Jubilée et les Sélections de Grains Nobles Riesling figurent parmi les grandes bouteilles d''Alsace. Adresse : 3 rue de la 1ère Armée, 68340 Riquewihr. Tél. : +33 3 89 47 92 15.'),
    ('Domaine Weinbach – Clos des Capucins', 'Kaysersberg, propriété de la famille Faller depuis 1898. Vin du Clos des Capucins (monopole de 12 ha), Riesling Schlossberg Grand Cru de référence. Adresse : Clos des Capucins, 68240 Kaysersberg. Tél. : +33 3 89 47 13 21.'),
    ('Domaine Léon Beyer', 'Eguisheim, l''une des maisons alsaciennes les plus reconnues à l''export. Style sec et minéral sur Riesling et Gewurztraminer. Adresse : 2 rue de la 1ère Armée, 68420 Eguisheim. Tél. : +33 3 89 41 41 05.'),
    ('Maison Josmeyer', 'Wintzenheim, fondée en 1854. Biodynamie depuis 2000. Le Fromenteau (Pinot Gris) et Hengst Grand Cru sont ses cuvées phares. Adresse : 76 rue Clemenceau, 68920 Wintzenheim. Tél. : +33 3 89 27 91 90.'),
    ('Krug', 'Reims, maison fondée en 1843 par Joseph Krug. Grande Cuvée (assemblage de 120+ vins de réserve), Clos du Mesnil (Chardonnay pur) et Clos d''Ambonnay parmi les références. Propriété LVMH. Adresse : 5 rue Coquebert, 51100 Reims. Tél. : +33 3 26 84 44 20.'),
    ('Bollinger', 'Aÿ, maison indépendante fondée en 1829. Pinot Noir majoritaire, style puissant. RD (Récemment Dégorgée) et Vieilles Vignes Françaises (pré-phylloxéra) sont des icônes. Adresse : 16 rue Jules-Lobet, 51160 Aÿ. Tél. : +33 3 26 53 33 66.'),
    ('Salon', 'Le Mesnil-sur-Oger, maison confidentielle ne produisant qu''un seul vin : un Blanc de Blancs millésimé, uniquement les meilleures années. Propriété Laurent-Perrier. Adresse : 5 rue de la Brèche, 51190 Le Mesnil-sur-Oger. Tél. : +33 3 26 57 51 65.'),
    ('Billecart-Salmon', 'Mareuil-sur-Aÿ, maison familiale indépendante fondée en 1818. Rosé Brut de référence, Blanc de Blancs et cuvée Nicolas François Billecart en tête de gamme. Adresse : 40 rue Carnot, 51160 Mareuil-sur-Aÿ. Tél. : +33 3 26 52 60 22.'),
    ('Louis Roederer', 'Reims, maison familiale fondée en 1776. Cristal (créé pour le tsar Alexandre II) reste la cuvée prestige la plus célèbre de Champagne. Adresse : 21 bd Lundy, 51053 Reims. Tél. : +33 3 26 40 42 11.'),
    ('Pol Roger', 'Épernay, maison fondée en 1849, fournisseur officiel de la Couronne britannique. Winston Churchill en fit sa cuvée favorite. Adresse : 1 rue Henri-Lelarge, 51200 Épernay. Tél. : +33 3 26 59 58 00.'),
    ('Gosset', 'Aÿ, plus ancienne maison de Champagne (1584). Style oxydatif assumé, vins sans malo-lactique. Grande Réserve et Celebris sont ses piliers. Adresse : 69 rue Jules-Blondeau, 51160 Aÿ. Tél. : +33 3 26 56 99 56.'),
    ('Jacquesson', 'Dizy, maison indépendante fondée en 1798. Cuvée 700+ (numérotée chaque année) en renouveau du style champenois. Champ Caïn et Vauzelle Terme en prestige. Adresse : 68 rue du Colonel-Fabien, 51530 Dizy. Tél. : +33 3 26 55 68 11.'),
    ('Ruinart', 'Reims, plus ancienne maison de Champagne encore en activité (1729). Blanc de Blancs R de Ruinart et Dom Ruinart Blanc de Blancs en vedette. Propriété LVMH. Adresse : 4 rue des Crayères, 51100 Reims. Tél. : +33 3 26 77 51 51.'),
    ('Domaine Marcel Lapierre', 'Villié-Morgon, pionnier du vin naturel avec Jules Chauvet. Morgon sans soufre ajouté, vendanges entières, style pur et fruité. Mathieu Lapierre perpétue l''héritage. Adresse : Les Chênes, 69910 Villié-Morgon. Tél. : +33 4 74 04 23 89.'),
    ('Domaine Jean Foillard', 'Villié-Morgon, dans la mouvance des « Quatre de Morgon ». Côte du Py et 3.14 sont ses cuvées phares, vinifications naturelles sur Gamay pur. Adresse : Méon, 69910 Villié-Morgon.'),
    ('Domaine des Terres Dorées – Jean-Paul Brun', 'Charnay, production en appellation Beaujolais et Beaujolais Villages. Gamay vinifié en blanc (L''Ancien) et rosé, style atypique et récompensé. Adresse : 69380 Charnay. Tél. : +33 4 78 47 93 45.'),
    ('Château Thivin', 'Odenas, propriété de la famille Geoffray sur la Côte de Brouilly depuis 1877. Cuvée Zaccharie et Claude Geoffray au sommet de la gamme. Adresse : Odenas, 69460 Saint-Étienne-la-Varenne. Tél. : +33 4 74 03 47 53.'),
    ('Mas de Daumas Gassac', 'Aniane, « Grand Cru » du Languedoc selon Robert Parker. Aimé Guibert a planté des Cabernet-Sauvignon sur une terroir de poudingue unique. Adresse : 34150 Aniane. Tél. : +33 4 67 57 71 28.'),
    ('Domaine Gérard Bertrand', 'Narbonne, l''un des plus importants producteurs du Languedoc en biodynamie. Château l''Hospitalet, Cigalus et Clos d''Ora figurent en haut de gamme. Adresse : Route de Narbonne Plage, 11100 Narbonne. Tél. : +33 4 68 45 28 50.'),
    ('Prieuré de Saint-Jean-de-Bébian', 'Pézenas, ex-propriété d''Alain Roux, aujourd''hui référence de la Coteaux-du-Languedoc. Assemblage Grenache, Syrah, Mourvèdre sur argilo-calcaires. Adresse : Route de Nizas, 34120 Pézenas.'),
    ('Domaine de Trévallon', 'Saint-Étienne-du-Grès, Eloi Dürrbach produit un vin hors-classement (IGP Alpilles) composé de Cabernet-Sauvignon et Syrah à parts égales. Adresse : 13103 Saint-Étienne-du-Grès. Tél. : +33 4 90 49 06 00.'),
    ('Château Simone', 'Meyreuil, monopole de l''appellation Palette, l''une des plus petites AOC de France. Rosé, rouge et blanc vieillissent admirablement. Adresse : 13114 Meyreuil. Tél. : +33 4 42 66 92 58.'),
    ('Château d''Esclans', 'La Motte-en-Provence, propriété Sacha Lichine, créateur du Whispering Angel, rosé le plus vendu au monde. Garrus en haut de gamme. Adresse : 83920 La Motte. Tél. : +33 4 94 60 40 40.'),
    ('Domaines Ott', 'Plusieurs propriétés en Provence (Château de Selle, Clos Mireille, Château Romassan). Références en Bandol et Côtes de Provence. Propriété Roederer. Adresse : 22 bd d''Aiguillon, 06600 Antibes. Tél. : +33 4 93 34 38 91.'),
    ('Domaine Henri Maire', 'Arbois, plus grand propriétaire du Jura, fondé en 1632. Vin Jaune et Vin de Paille en référence, gamme large sur toutes les AOC jurassiennes. Adresse : Château Montfort, 39600 Arbois. Tél. : +33 3 84 66 12 34.'),
    ('Domaine Overnoy-Houillon', 'Pupillin, Pierre Overnoy fut le pionnier du vin sans soufre en France. Emmanuel Houillon perpétue l''œuvre sur Savagnin, Poulsard et Trousseau. Adresse : Pupillin, 39600 Arbois.'),
    ('Domaine Ganevat', 'Rotalier, Jean-François Ganevat produit une multitude de cuvées parcellaires sur toutes les AOC du Jura, en biodynamie. Vins rarissimes et très recherchés. Adresse : La Combe, 39190 Rotalier.'),
    ('Domaine Belluard', 'Ayze, Dominique Belluard est le défenseur du Gringet, cépage autochtone de Savoie. Son Ayze Brut Méthode Traditionnelle et Les Alpes font référence. Adresse : 741 route d''Ayze, 74130 Ayze. Tél. : +33 4 50 97 11 48.'),
    ('Gilles Berlioz', 'Chignin (Savoie), producteur star du Chignin-Bergeron (Roussanne). Ses vins affichent une richesse et une complexité qui surprennent ceux qui sous-estiment la Savoie. Adresse : Chignin, 73800 Savoie.'),
    ('Domaine des Ardoisières', 'Cevins (Savoie), vignoble d''altitude créé avec l''inspiration de Michel Grisard sur des terrasses de schiste ardoisier en bord d''Isère. Cépages autochtones : Mondeuse, Jacquère, Persan. L''une des propriétés les plus ambitieuses de la viticulture alpine française. Adresse : Cevins, 73730 Savoie.'),
    ('Domaine Raveneau', 'Chablis, fondé par François Raveneau en 1948. Considéré comme le plus grand domaine de l''appellation. Grands Crus Blanchot, Les Clos, Valmur et Premiers Crus Montée de Tonnerre, Chapelot. Vins d''une minéralité et d''une longévité exceptionnelles. Adresse : 89800 Chablis.'),
    ('Domaine Vincent Dauvissat', 'Chablis, aux côtés de Raveneau, l''autre référence absolue de l''appellation. 11 ha comprenant les Grands Crus Les Clos et Les Preuses. Vins d''une pureté et d''une profondeur minérale remarquables. Adresse : 8 rue Émile-Zola, 89800 Chablis.'),
    ('Domaine William Fèvre', 'Chablis, le plus grand propriétaire individuel en Grand Cru (15,2 ha sur les 101 ha de l''appellation). Fondé en 1959, appartient depuis au groupe Bouchard Père et Fils (Henriot). Chablis précis et typé à tous les niveaux de gamme. Adresse : 10 rue Jules-Rathier, 89800 Chablis. Tél. : +33 3 86 18 14 37.'),
    ('Domaine Long-Depaquit', 'Chablis, l''un des plus anciens domaines de l''appellation, aujourd''hui propriété de la maison Albert Bichot. Détenteur du monopole La Moutonne, Grand Cru à cheval sur Vaudésir et Preuses. Adresse : 45 rue Auxerroise, 89800 Chablis. Tél. : +33 3 86 42 11 13.'),
    ('Domaine Trapet Père et Fils', 'Gevrey-Chambertin, domaine biodynamique possédant Chambertin, Chapelle-Chambertin et Latricières-Chambertin. Jean-Louis Trapet signe des vins d''une pureté et d''une élégance exemplaires. Adresse : 53 route de Beaune, 21220 Gevrey-Chambertin.'),
    ('Domaine Rossignol-Trapet', 'Gevrey-Chambertin, branche distincte de la famille Trapet produisant des Grands Crus Chambertin et Latricières en biodynamie. Style traditionnel attaché à l''expression du terroir. Adresse : 4 rue de la Petite-Issue, 21220 Gevrey-Chambertin. Tél. : +33 3 80 51 87 26.'),
    ('Domaine Drouhin-Laroze', 'Gevrey-Chambertin, l''un des plus grands propriétaires de Grands Crus en Côte de Nuits : Clos de Bèze, Chambertin, Bonnes-Mares, Clos Vougeot. Vins aromatiques et élégants à fort potentiel de garde. Adresse : 20 rue du Gaizot, 21220 Gevrey-Chambertin.'),
    ('Domaine Mugneret-Gibourg', 'Vosne-Romanée, domaine de 8 ha conduit par les sœurs Mugneret. Vignes en Vosne-Romanée, Nuits-Saint-Georges Premiers Crus, Ruchottes-Chambertin et Échezeaux. Vins d''une grande élégance et d''un potentiel de garde remarquable. Adresse : 5 rue des Grands-Crus, 21700 Vosne-Romanée.'),
    ('Domaine Hudelot-Noëllat', 'Chambolle-Musigny, conduit par Charles Van Canneyt (petit-fils du fondateur). Chambolle, Vosne-Romanée et Grands Crus Richebourg et Romanée-Saint-Vivant au sommet de la gamme. Qualité en forte progression depuis la reprise. Adresse : 5 Ancienne RN 74, 21220 Chambolle-Musigny.'),
    ('Domaine Henri Boillot', 'Puligny-Montrachet, établi en 1885, produit des Grands Crus blancs (Bâtard-Montrachet, Chevalier-Montrachet) et des rouges de Volnay. L''une des références les plus respectées de la Côte de Beaune. Adresse : 21190 Puligny-Montrachet.'),
    ('Domaine A. & P. de Villaine', 'Bouzeron (Côte Chalonnaise), propriété du co-gérant de la DRC Aubert de Villaine. Aligoté de Bouzeron de référence et Pinot Noir/Chardonnay de niveau Côte d''Or. Essentiel pour approcher la philosophie DRC à des prix accessibles. Adresse : 2 rue de la Fontaine, 71150 Bouzeron.'),
    ('Maison Louis Latour', 'Beaune, l''un des négociants et propriétaires les plus importants de Bourgogne. Vastes domaines en Grands Crus dont le Château Corton-Grancey et le Corton-Charlemagne. Production de 350 000 caisses/an. Adresse : 18 rue des Tonneliers, 21204 Beaune.'),
    ('Domaine Merlin', 'La Roche-Vineuse, Olivier et Corinne Merlin sont devenus des références du Pouilly-Fuissé et du Mâcon depuis 1987. Trois cuvées distinctes de Pouilly-Fuissé démontrent que le Mâconnais peut rivaliser avec la Côte de Beaune. Adresse : La Roche-Vineuse, 71960.'),
    ('Domaine de la Soufrandière – Bret Brothers', 'Vinzelles, Jean-Guillaume et Jean-Philippe Bret produisent des vins parcellaires en biodynamie, parmi les plus convaincants du Mâconnais. Pouilly-Fuissé « En Buland » de référence. Adresse : Vinzelles, 71680.'),
    ('Domaine Jean Thévenet – Domaine de la Bongran', 'Clessé, pionnier des styles vendanges tardives et botryticées dans le Mâconnais. Viré-Clessé vieilles vignes riches et concentrés d''une originalité unique dans le sud de la Bourgogne. Adresse : Clessé, 71260.'),
    ('Château Montrose', 'Deuxième Grand Cru Classé de Saint-Estèphe (1855), vins puissants et structurés nécessitant une longue garde. Les millésimes 2009 et 2010 comptent parmi les meilleurs vins jamais produits à Bordeaux. Propriété de la famille Bouygues depuis 2006. Adresse : 33180 Saint-Estèphe. Tél. : +33 5 56 73 23 45.'),
    ('Château Phélan Ségur', 'Saint-Estèphe, l''un des meilleurs Crus Bourgeois de l''appellation. Vins d''élégance et de complexité rivalisant avec bien des crus classés. 70 ha sous vigne, terroir de graves et argiles. Adresse : 33180 Saint-Estèphe.'),
    ('Château Haut Marbuzet', 'Saint-Estèphe, Cru Bourgeois de Henri Duboscq. Style hédoniste et généreusement boisé, parmi les vins les plus séduisants à prix accessible de tout le Médoc. Adresse : 33180 Saint-Estèphe.'),
    ('Château Branaire-Ducru', 'Quatrième Grand Cru Classé de Saint-Julien (1855). Style floral et épicé caractéristique, profondément amélioré depuis les années 1990. Adresse : 1 chemin du Bourdieu, 33250 Saint-Julien-Beychevelle. Tél. : +33 5 56 59 25 86.'),
    ('Château Léoville Poyferré', 'Deuxième Grand Cru Classé de Saint-Julien (1855), le troisième des Léoville. Style opulent sous la direction de Didier Cuvelier depuis les années 1990. Aujourd''hui l''égal de ses cousins Léoville. Adresse : 38 rue de Saint-Julien, 33250 Saint-Julien-Beychevelle. Tél. : +33 5 56 59 66 79.'),
    ('Château Talbot', 'Quatrième Grand Cru Classé de Saint-Julien (1855), nommé d''après le général anglais vaincu à Castillon en 1453. Vin généreux et charnu, production importante. Le blanc Caillou Blanc est également notable. Adresse : 33250 Saint-Julien-Beychevelle.'),
    ('Château Grand Puy Lacoste', 'Cinquième Grand Cru Classé de Pauillac (1855), régulièrement au-dessus de son rang. Propriété de la famille Borie depuis 1978. Pauillac classique, minéral et ferme, d''excellent vieillissement. Adresse : 33250 Pauillac.'),
    ('Château d''Armailhac', 'Cinquième Grand Cru Classé de Pauillac (1855), propriété Rothschild (Mouton). Anciennement Mouton Baron Philippe puis Mouton Baronne Philippe. Pauillac typé et de bonne garde à prix modéré. Adresse : 33250 Pauillac.'),
    ('Château Rauzan-Ségla', 'Deuxième Grand Cru Classé de Margaux (1855), propriété de Chanel depuis 1994. Style soyeux et parfumé, classiquement margalais. Parmi les plus améliorés de l''appellation sur les deux dernières décennies. Adresse : 33460 Margaux.'),
    ('Château Brane-Cantenac', 'Deuxième Grand Cru Classé de Margaux (1855), propriété d''Henri Lurton. 90 ha, style élégant et fruité, finesse caractéristique de l''appellation. Adresse : 33460 Cantenac.'),
    ('Château Giscours', 'Troisième Grand Cru Classé de Margaux / Labarde (1855). Style plus corpulent que la moyenne de l''appellation. 80 ha sous vigne, excellent rapport qualité-prix parmi les crus classés. Adresse : 33460 Labarde.'),
    ('Château Smith Haut Lafitte', 'Grand Cru Classé de Graves, Pessac-Léognan. Spectaculairement relancé par Florence et Daniel Cathiard depuis 1990. Le blanc (Sauvignon Blanc dominant) compte parmi les meilleurs secs de Bordeaux. Berceau des Sources de Caudalie. Adresse : 33650 Martillac. Tél. : +33 5 57 83 11 22.'),
    ('Château Haut-Bailly', 'Grand Cru Classé de Graves, Pessac-Léognan. Produit exclusivement du rouge sur 30 ha. Style velouté et approchable dissimulant une grande profondeur. Propriété Wilmers depuis 1998. Adresse : 103 av. de Cadaujac, 33850 Léognan. Tél. : +33 5 56 20 50 27.'),
    ('Château Malartic-Lagravière', 'Grand Cru Classé de Graves, Pessac-Léognan. Entièrement rénové par la famille Bonnie depuis 1997. Rouge et blanc d''une grande précision ; le blanc (Sauvignon Blanc, Sémillon) est une référence de l''appellation. Adresse : 33850 Léognan.'),
    ('Château L''Évangile', 'Pomerol, propriété Rothschild (Lafite) depuis 1990. Jouxte Pétrus et Cheval Blanc sur graves et argiles. Merlot concentré structuré par le Cabernet Franc. L''un des tous premiers Pomerol. Adresse : 33500 Pomerol.'),
    ('Château Clinet', 'Pomerol, l''un des plus structurés et de plus longue garde de l''appellation. Merlot sur sols argilo-graveleux, propriété de la famille Laborde depuis 1991. Adresse : 33500 Pomerol.'),
    ('Château Trotanoy', 'Pomerol, grand domaine historique géré par Moueix (gérant de Pétrus). Merlot vieilles vignes sur argiles, vins denses et longilignes. Dans le top 5 de l''appellation. Adresse : 33500 Pomerol.'),
    ('Château Le Pin', 'Pomerol, créé en 1979 par Jacques Thienpont. 2,5 ha seulement, l''un des vins les plus rares et chers au monde. Style riche et crémeux, demande extrêmement supérieure à l''offre. Adresse : 33500 Pomerol.'),
    ('Château Canon', 'Premier Grand Cru Classé B de Saint-Émilion, propriété de Chanel depuis 1996. Vins d''une grande élégance depuis le plateau calcaire à l''ouest du village. Référence pour la finesse de l''appellation. Adresse : 33330 Saint-Émilion.'),
    ('Château La Gaffelière', 'Premier Grand Cru Classé B de Saint-Émilion, sur les pentes du village. Assemblage à forte proportion de Cabernet Franc (≈ 50 %). Vins parfumés, élégants et profondément terroir. Adresse : 33330 Saint-Émilion.'),
    ('Château Beau-Séjour Bécot', 'Premier Grand Cru Classé de Saint-Émilion depuis 2022. Vins puissants sur calcaires du plateau, propriété familiale. Vieilles vignes (moy. 40 ans), biodynamie en cours. Adresse : 33330 Saint-Émilion.'),
    ('Domaine Auguste Clape', 'Cornas, la référence de l''appellation. Auguste et Pierre-Marie Clape produisent un Cornas de vieilles vignes sur granit, collectible et nécessitant dix ans de garde. Adresse : 146 av. du Colonel-Rousset, 07130 Cornas.'),
    ('Domaine Thierry Allemand', 'Cornas, 3,5 ha donnant deux cuvées — Chaillot et Reynard — parmi les plus recherchées du Rhône. Vinification naturelle, Syrah d''une pureté et d''une profondeur extraordinaires. Adresse : 07130 Cornas.'),
    ('Domaine Alain Graillot', 'Pont-de-l''Isère (Crozes-Hermitage), fondé en 1985 sans expérience préalable. A mis Crozes-Hermitage sur la carte du vin fin. La cuvée « La Guiraude » est l''une des meilleures de l''appellation. Adresse : 105 chemin des Chênes-Verts, 26600 Pont-de-l''Isère. Tél. : +33 4 75 84 67 52.'),
    ('Domaine Yves Cuilleron', 'Chavanay, l''un des producteurs les plus dynamiques du Rhône nord. Condrieu en Viognier, Côte-Rôtie et Saint-Joseph de qualité. Expérimentation sur des parcelles et des styles variés. Adresse : Verlieu, 42410 Chavanay.'),
    ('Domaine Stéphane Ogier', 'Ampuis, Côte-Rôtie. Stéphane Ogier a hissé ce domaine au rang des plus célébrés de l''appellation. Cuvée parcellaire « Lancement » très recherchée. Produit aussi Saint-Joseph et Condrieu. Adresse : 69420 Ampuis.'),
    ('Domaine Marc Sorrel', 'Tain-l''Hermitage, petit domaine produisant deux Hermitage — « Le Gréal » (rouge) et « Les Rocoules » (blanc) — d''une grande longévité. Style traditionnel, élevage long. Adresse : 26600 Tain-l''Hermitage.'),
    ('Domaine Santa Duc', 'Gigondas, Yves Gras conduit le domaine en biodynamie. « Les Hautes Garrigues » est une référence de l''appellation. Produit aussi d''excellents Côtes du Rhône Villages. Adresse : 157 chemin des Hautes-Garrigues, 84190 Gigondas. Tél. : +33 4 90 65 84 49.'),
    ('Château de Saint-Cosme', 'Gigondas, domaine historique du XVe siècle, conduit par Louis Barruol. Gigondas de premier plan, parmi les meilleurs de l''appellation. Produit aussi en Côtes du Rhône. Adresse : route de Gigondas, 84190 Gigondas.'),
    ('Domaine Les Pallières', 'Gigondas, co-propriété des familles Brunier (Vieux Télégraphe) et Kermit Lynch. Grenache vieilles vignes sur sols variés, garrigue intense. Une des adresses authentiques de l''appellation. Adresse : 84190 Gigondas.'),
    ('Domaine de la Mordorée', 'Tavel, producteur exceptionnel en Lirac et Tavel. La cuvée « La Reine des Bois » compte parmi les meilleurs vins du Rhône méridional. Produit aussi un Châteauneuf-du-Pape sérieux. Adresse : chemin des Oliviers, 30126 Tavel.'),
    ('Domaine Montirius', 'Sarrians, Vacqueyras et Gigondas. Éric et Christine Saurel en biodynamie stricte. Parmi les producteurs les plus passionnants du Rhône sud, vins de terroir précis. Adresse : 84260 Sarrians.'),
    ('Domaine François Cotat', 'Chavignol (Sancerre), vieilles vignes Sauvignon sur Les Monts Damnés et La Grande Côte. Très faible production, vinification sans intrant. Vins d''une texture et d''une longévité rares. Adresse : Bourg de Chavignol, 18300 Sancerre. Tél. : +33 2 48 78 01 41.'),
    ('Domaine Lucien Crochet', 'Bué (Sancerre), important domaine familial producteur de blanc et rouge réguliers. La cuvée Prestige pour un vieillissement à moyen terme. Adresse : Bué, 18300 Sancerre.'),
    ('Domaine Alphonse Mellot', 'Sancerre, 18 générations de vignerons. La Moussière en vin phare, biodynamie en cours. Gamme parcellaire terroiriste sous la direction d''Alphonse Mellot fils. Pilier de l''appellation. Adresse : 18300 Sancerre.'),
    ('Domaine Henry Pellé', 'Morogues (Menetou-Salon), référence de l''appellation voisine de Sancerre. Sauvignon Blanc et Pinot Noir de qualité comparable à Sancerre, à des prix plus accessibles. Adresse : Morogues, 18220.'),
    ('Domaine du Clos Naudin – Philippe Foreau', 'Vouvray, l''un des domaines les plus célèbres de l''appellation. Gamme complète sec-moelleux selon le millésime, Chenin vieilles vignes. Mousseux méthode traditionnelle exemplaire. Adresse : 14 rue de la Croix-Buisée, 37210 Vouvray. Tél. : +33 2 47 52 71 46.'),
    ('Domaine Bernard Baudry', 'Cravant-les-Coteaux (Chinon), Mathieu et Bernard Baudry en tête de Chinon avec des Cabernet Franc parcellaires. « Croix Boissée » pour une longue garde, « Domaine » et « Granges » en entrée de gamme. Adresse : 66 route de Chinon, 37500 Cravant-les-Coteaux. Tél. : +33 2 47 93 15 79.'),
    ('Domaine Charles Joguet', 'Sazilly (Chinon), Charles Joguet a forgé la réputation de l''appellation pour le Cabernet Franc sérieux. Le Clos de la Dioterie (vignes de 80 ans) est une référence mondiale. Adresse : 37220 Sazilly.'),
    ('Domaine de la Pépière', 'Maisdon-sur-Sèvre, Marc Ollivier prouve depuis 30 ans que le Muscadet peut vieillir. Clos des Briords admirable après 20 ans de garde. Agriculture biologique. Adresse : 44690 Maisdon-sur-Sèvre.'),
    ('Domaine de l''Écu', 'Le Landreau (Muscadet Sèvre-et-Maine), premier domaine biodynamique de l''appellation. Cuvées par type de sol (Granite, Orthogneiss, Gabbro) révolutionnant la compréhension du terroir muscadetois. Adresse : 44430 Le Landreau.'),
    ('Domaine Baumard', 'Rochefort-sur-Loire, pilier de l''Anjou blanc. Jean Baumard a contribué à faire reconnaître les Quarts de Chaume en Grand Cru. Savennières sec et moelleux Coteaux du Layon de référence. Adresse : 49190 Rochefort-sur-Loire.'),
    ('Domaine Albert Boxler', 'Niedermorschwihr, l''un des grands domaines alsaciens en Riesling Grand Cru Sommerberg (avec différentes cuvées par secteur). Précision minérale et potentiel de garde exceptionnels. Adresse : 78 rue des Trois-Épis, 68230 Niedermorschwihr.'),
    ('Domaine Ostertag', 'Epfig, André Ostertag produit des vins alsaciens influencés par la Bourgogne, vinifiés en fûts. Grand Cru Muenchberg Riesling parmi les plus complexes d''Alsace. Philosophie du lieu-dit. Adresse : 87 rue Finkwiller, 67680 Epfig.'),
    ('Domaine Albert Mann', 'Wettolsheim, biodynamie depuis 1997. Grands Crus Schlossberg, Furstentum et Hengst. Vins d''une pureté et d''un sens du terroir exemplaires. Adresse : 13 rue du Château, 68920 Wettolsheim.'),
    ('Domaine Schlumberger', 'Guebwiller, le plus grand propriétaire de Grands Crus en Alsace (140 ha sur coteaux pentus). Kitterlé, Kessler, Saering, Spiegel. Style riche et opulent, Riesling Kitterlé parmi les plus longilignes d''Alsace. Adresse : 100 rue Théodore-Deck, 68501 Guebwiller.'),
    ('Domaine Rolly Gassmann', 'Rohrschwihr, large gamme sur plusieurs Grands Crus et lieux-dits. Style généreux, aromatique et apte au vieillissement. Fort sur Pinot Gris, Gewurztraminer et Riesling. Adresse : 2 rue de l''Église, 68590 Rohrschwihr.'),
    ('Taittinger', 'Reims, l''une des dernières grandes maisons familiales de Champagne. Style Chardonnay dominant, finesse comme ligne directrice. Comtes de Champagne Blanc de Blancs, l''une des grandes cuvées prestige. Vastes propriétés en Grand Cru Chardonnay. Adresse : 9 place Saint-Nicaise, 51100 Reims.'),
    ('Philipponnat', 'Mareuil-sur-Aÿ, maison de référence depuis le XVIe siècle. Le Clos des Goisses — parcelle en forte pente exposée sud-ouest — est l''un des plus grands Champagnes mono-parcellaires. Adresse : 13 rue du Pont, 51160 Mareuil-sur-Aÿ.'),
    ('Domaine Jacques Selosse', 'Avize, Anselme Selosse est la figure la plus influente du mouvement récoltant-manipulant. Vinification en fûts, approche terroiriste, nuance oxydative signature. V.O. et Initial sont des vins cultes. Adresse : 22 rue Ernest-Vallée, 51190 Avize.'),
    ('Egly-Ouriet', 'Ambonnay (Grand Cru), maison récoltante de référence. Pinot Noir central, longue vinification sur lies, VP Extra Brut vieilles vignes parmi les meilleurs Champagne grower. Adresse : 15 rue de Trépail, 51150 Ambonnay.'),
    ('Pierre Péters', 'Le Mesnil-sur-Oger (Grand Cru), spécialiste du Blanc de Blancs pur et linéaire. « Cuvée Spéciale Les Chétillons » parmi les Champagne récoltants les plus recherchés. Adresse : 26 rue des Lombards, 51190 Le Mesnil-sur-Oger. Tél. : +33 3 26 57 50 32.'),
    ('Larmandier-Bernier', 'Vertus (Côte des Blancs), biodynamie certifiée. Pierre et Sophie Larmandier produisent des Chardonnay d''une pureté calcaire exemplaire. « Terre de Vertus » non-dosé, une définition du récoltant-manipulant. Adresse : 19 av. du Général-de-Gaulle, 51130 Vertus. Tél. : +33 3 26 52 13 24.'),
    ('Drappier', 'Urville (Côte des Bar, Aube), maison familiale championne du Pinot Noir aubois et des approches à faible intervention. Quattuor (cépages anciens) et Brut Nature sans soufre, des vins uniques. Adresse : rue des Vignes, 10200 Urville.'),
    ('Chartogne-Taillet', 'Merfy, Alexandre Chartogne en biodynamie, vinifie chaque lieu-dit séparément. « Sainte Anne » et « Les Barres » parmi les Champagne grower les plus convaincants. Adresse : 51220 Merfy.'),
    ('Château des Jacques', 'Romanèche-Thorins, propriété de Louis Jadot. Cuvées parcellaires de Moulin-à-Vent et Morgon vinifiées à la bourguignonne. Montre le potentiel de garde des crus du Beaujolais. Adresse : 71570 Romanèche-Thorins.'),
    ('Domaine Jean-Claude Lapalu', 'Saint-Lager (Brouilly / Côte de Brouilly), agriculture biologique, vins de terroir en viticulture naturelle. Successeur de la philosophie « Gang de Morgon ». Adresse : 69220 Saint-Lager.'),
    ('Grange des Pères', 'Aniane (IGP Hérault), Laurent Vaillé (formé chez Jayer et Chave) produit l''un des vins les plus profonds du Languedoc : Syrah, Mourvèdre, Cabernet. Production confidentielle, prix de Grand Cru. Le blanc est également exceptionnel. Adresse : 34150 Aniane.'),
    ('Domaine Léon Barral', 'Cabrerolles (Faugères), biodynamie radicale avec chevaux et animaux intégrés au vignoble. Vins expressifs sur schistes de Faugères : Grenache, Cinsault, Carignan, Mourvèdre de grande garde. Adresse : Lenthéric, 34480 Cabrerolles.'),
    ('Mas Jullien', 'Saint-Saturnin-de-Lucian (Terrasses du Larzac), Olivier Jullien est l''un des pères fondateurs de la qualité en Languedoc depuis 1985. Assemblages complexes sur calcaires, vins structurés et élégants. Adresse : 34725 Saint-Saturnin-de-Lucian.'),
    ('Domaine Aupilhac', 'Montpeyroux (Coteaux du Languedoc), Sylvain Fadat produit des rouges minéraux et structurés sur calcaires. « Lou Maset » et « Campagne » démontrent le potentiel de ce terroir sous-estimé. Adresse : 28 rue du Plô, 34150 Montpeyroux.'),
    ('Domaine Mas Amiel', 'Maury (Roussillon), référence du Maury Vin Doux Naturel sur schistes noirs. Produit à la fois le style oxydatif traditionnel (bonbonnes en plein air) et des styles fruités modernes. Adresse : 66460 Maury.'),
    ('Domaine de la Rectorie – Parcé Frères', 'Banyuls-sur-Mer, Marc et Thierry Parcé produisent le meilleur Banyuls de style rubis (frais et fruité) et des Collioure rouges et blancs de référence sur la Côte Vermeille. Adresse : 54 av. du Puig-del-Mas, 66650 Banyuls-sur-Mer.'),
    ('Domaine de Cazes', 'Rivesaltes, le plus grand vignoble biodynamique certifié de France (220 ha). Côtes du Roussillon, Rivesaltes et Muscat de Rivesaltes sur une gamme large et d''une qualité remarquable pour l''échelle de production. Adresse : 4 rue Francisco-Ferrer, 66600 Rivesaltes.'),
    ('Château Montus – Château Bouscassé', 'Maumusson-Laguian (Madiran), Alain Brumont a ressuscité le Madiran et le Pacherenc. Ses deux châteaux produisent des Tannat de référence parmi les vins les plus longilignes de France hors Bordeaux. Adresse : 32400 Maumusson-Laguian. Tél. : +33 5 62 69 74 67.'),
    ('Château du Cèdre', 'Vire-sur-Lot (Cahors), Pascal Verhaeghe, pionnier de l''agriculture biologique dans le Cahors. Malbec sur argilo-calcaires, « Le Cèdre » parmi les meilleurs de l''appellation. Adresse : Bru, 46700 Vire-sur-Lot. Tél. : +33 5 65 36 53 87.'),
    ('Clos Triguedina', 'Vire-sur-Lot (Cahors), propriété des Baldès depuis 1830, l''un des fondateurs de l''AOC moderne. 65 ha de Malbec sur les meilleures terrasses. « Malbec du Clos » : puissance et terroir. Adresse : 46700 Vire-sur-Lot.'),
    ('Domaine Cauhapé', 'Monein (Jurançon), Henri Ramonteu a relancé le Jurançon de qualité depuis les années 1980. Petit et Gros Manseng en sec et moelleux. « Noblesse du Temps » et « Folie de Janvier » parmi les grands liquoreux français. Adresse : 108 route de Cardesse, 64360 Monein. Tél. : +33 5 59 21 33 02.'),
    ('Domaine Tempier', 'Le Plan du Castellet (Bandol), domaine historique de la famille Peyraud, porte-drapeau du Bandol depuis plusieurs générations. Mourvèdre-dominant en rouge, rosé de référence, cuvées parcellaires Migoua, Tourtine et Cabassaou parmi les meilleurs vins de Provence. Adresse : famille Peyraud, 83330 Le Plan du Castellet. Tél. : +33 4 94 98 70 21.'),
    ('Château Pibarnon', 'La Cadière-d''Azur (Bandol), domaine en altitude (300 m) donnant des Mourvèdre d''une fraîcheur et d''une élégance inhabituelles pour l''appellation. 50 ha de vieilles vignes. Parmi les trois premiers de Bandol. Adresse : 410 chemin de la Croix-des-Signaux, 83740 La Cadière-d''Azur.'),
    ('Château Pradeaux', 'Saint-Cyr-sur-Mer (Bandol), domaine ultra-traditionnel de la famille Portalis depuis 1752. Élevage en foudre jusqu''à 4 ans avant mise. Vins parmi les plus austères et les plus longilignes de l''appellation. Adresse : 676 chemin des Pradeaux, 83270 Saint-Cyr-sur-Mer.'),
    ('Domaine Hauvette', 'Saint-Rémy-de-Provence (Les Baux-de-Provence), agriculture biologique. Dominique Hauvette produit des vins blancs (Roussanne, Marsanne) et rouges (Syrah, Grenache) parmi les plus intellectuels de Provence. Adresse : 13210 Saint-Rémy-de-Provence.'),
    ('Domaine Antoine Arena', 'Patrimonio (Haute-Corse), la famille Arena vinifie depuis plus de 200 ans. Antoine-Marie Arena signe des Nielluccio rouges et Vermentino blancs de référence, ainsi qu''un Muscat du Cap Corse exceptionnel. Adresse : Morta Maïo, 20253 Patrimonio. Tél. : +33 4 95 37 08 27.'),
    ('Domaine Comte Abbatucci', 'Sollacaro (Ajaccio), Jean-Charles Abbatucci est probablement le vigneron le plus reconnu de Corse. 21 ha en biodynamie dans la vallée du Taravo, cépages corses autochtones rarissimes (Sciacarello, Barbarossa, etc.). Adresse : Domaine de Fiumicicoli, 20112 Sollacaro.'),
    ('Domaine de Torraccia', 'Lecci (Porto-Vecchio, Corse-du-Sud), Christian Imbert a contribué à la renaissance du vin corse de qualité dès les années 1960–70. Nielluccio et Sciacarello sur granit. Adresse : Lecci, 20137 Porto-Vecchio.'),
    ('Domaine Stéphane Tissot', 'Montigny-lès-Arsures (Arbois), le producteur le plus ambitieux du Jura. 50 ha en biodynamie, gamme considérable : Vin Jaune, Crémant, Chardonnay, Savagnin, Poulsard, Trousseau en cuvées parcellaires. Adresse : 39 route de Lyon, 39600 Montigny-lès-Arsures. Tél. : +33 3 84 66 08 27.'),
    ('Domaine de la Tournelle', 'Arbois, Évelyne et Pascal Clairet depuis 1991. Vins naturels expressifs en Poulsard, Trousseau et Chardonnay. « Uva Arbosiana » et fleur-de-savagnin blancs sont des classiques du Jura naturel. Adresse : 5 place de la Petite-Place, 39600 Arbois.'),
    ('Domaine Michel Gahier', 'Montigny-lès-Arsures (Arbois), élevage sous voile assumé pour le Savagnin, style oxydatif précis et frais. Vin Jaune de référence de la région. 7 ha familiaux depuis 1947. Adresse : 39600 Montigny-lès-Arsures.'),
    ('Le Rocher des Violettes', 'Dierre (Montlouis-sur-Loire), fondé en 2005 par Xavier Weisskopf. 17 ha : 14 en Chenin Blanc sur vieilles vignes, 3 en cépages rouges. Vinification biologique, fermentations spontanées, soufre minimal. Adresse : 34 rue de la Roche, Dierre, 37150 Saint-Martin-le-Beau. Tél. : +33 2 47 23 52 08.'),
    ('Domaine Thibert Père et Fils', 'Fuissé (Pouilly-Fuissé), sept générations de vignerons. Plus de 20 ha sur l''ensemble des appellations du Mâconnais sud. Certification HVE, vendanges manuelles nocturnes. Adresse : 20 rue Adrien-Arcelin, 71960 Fuissé. Tél. : +33 3 85 27 02 66.')
''');
}
